name: On push

on:
  workflow_dispatch:
    inputs:
      changed-files:
        description: Changed files for processing
        type: string
  push:
    branches:
      - master

jobs:
  uplift:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          separator: ','
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ogc-na
      - name: Process files
        env:
          DB_USERNAME: admin
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          MOD_FILES=${{ steps.changed-files.outputs.all_changed_files }},${{ inputs.changed-files }}
          echo Changed files: ${MOD_FILES}
          python -m ogc.na.update_vocabs catalog.ttl \
            --base-uri https://raw.githubusercontent.com/${{github.repository}}/${{github.ref_name}} \
            --update --graph-store ${{ vars.UPLOAD_GRAPH_STORE_URL }} \
            -m ${MOD_FILES}
      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Semantic uplift on push"
          default_author: github_actions